[tool]
[tool.poetry]
name = "TakashiUserbot_Deployer"
version = "1.0"
description = "Automatic Deploy SiriUserBot to Heroku"
authors = ["Takashi <Takashi@erkanoyunda.tech>"]
[tool.poetry.dependencies]
python = "^3.8"
bs4 = "*"
gitpython = "*"
heroku3 = "*"
requests = "*"
rich = "*"
telethon = "*"
